version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mernproject
    depends_on:
      - mongo
    command: sh -c "until nc -z mongo 27017; do sleep 1; done && npm start"
  mongo:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: