version: '3.0'
services:
  app:
    build: .
    command: npm run development
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mernproject
      - NODE_ENV=development
      - JWT_SECRET=YOUR_secret_key
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - mern-network

  mongo:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --bind_ip_all
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data: