apiVersion: v1
kind: Pod
metadata:
  name: full-stack-pod
  labels:
    app: full-stack
spec:
  containers:
    - name: mongodb
      image: mongo:4.2.0
      ports:
        - containerPort: 27017
    - name: mongo-express
      image: mongo-express
      ports:
        - containerPort: 8081
      env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "localhost"
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "password"
    - name: mern-app
      image: mern-social:latest
      ports:
        - containerPort: 3000
      env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017/mernproject"
        - name: NODE_ENV
          value: "development"
        - name: JWT_SECRET
          value: "your-jwt-secret"
        - name: PORT
          value: "3000"
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: ssl-certs
          mountPath: /etc/nginx/ssl
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
    - name: ssl-certs
      secret:
        secretName: ssl-certs