apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
      - name: mern-app
        image: mern-social:latest
        imagePullPolicy: Never
        command: ["npm"]
        args: ["run", "development"]
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/mernproject"
        - name: NODE_ENV
          value: "development"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: jwt-secret
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-app
spec:
  type: LoadBalancer
  selector:
    app: mern-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000